# Generated by Django 2.2.14 on 2023-03-20 02:59

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USPostalCodeField(max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=localflavor.us.models.USZipCodeField(max_length=10),
        ),
    ]
