# Generated by Django 2.2.14 on 2023-03-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_id',
            field=models.CharField(default='xxx', max_length=200),
            preserve_default=False,
        ),
    ]
