# Generated by Django 2.2.14 on 2023-03-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(default='x', max_length=20),
            preserve_default=False,
        ),
    ]
