# Generated by Django 2.2.14 on 2023-03-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coupon_coupon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
