# Generated by Django 2.2.14 on 2023-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230322_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
