# Generated by Django 2.2.14 on 2023-03-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orderitem_ordered_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
