# Generated by Django 2.2 on 2023-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230326_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
